datacite/bracco

- app/templates/components/model-search.hbs
This fixes the issue. Also fixes the broken search button. This change disables typeahead.
> trigger search on enter instead of key-up Closes #30

- app/components/application-header.js
- app/components/menu-user.js
- app/helpers/jwt-host.js
- app/services/current-user.js
- app/templates/components/application-header.hbs
- app/templates/components/menu-user.hbs
- ember-electron/main.js
- ember-electron/test-main.js
- package.json
- yarn.lock
Primary use case is the App, so that external links are sent to default browser. But this also avoids a refresh of the whole page when clicking on `home` navigation link.
> open external links in separate window

- app/index.html
- config/environment.js
- package-lock.json
- package.json
- yarn.lock
Hopefully addresses issues with IE11: https://github.com/datacite/bracco/issues/13. And reduces download size of bracco and dependencies.
> use polyfill.io with default settings

- app/components/client-transfer.js
- app/templates/components/client-transfer.hbs
- config/environment.js
closes #26 
This is an usersnap https://usersnap.com/a/#/datacite/p/datacite-41ebcc0f/278
> Disable trasnfer buttons unless a client is specified

- .travis.yml
- app/components/client-show.js
- app/components/provider-show.js
- app/models/client.js
- app/models/provider.js
- app/templates/components/client-show.hbs
- app/templates/components/provider-show.hbs
Adapting to changes in backend, using `password-input` instead of `password`.
> Clean up set password functionality

- app/authenticators/jwt.js
- app/controllers/application.js
- app/controllers/send-link.js
- app/router.js
- app/routes/application.js
- app/routes/send-link.js
- app/services/current-user.js
- app/templates/components/client-show.hbs
- app/templates/components/menu-user.hbs
- app/templates/components/provider-show.hbs
- app/templates/send-link.hbs
- app/templates/sign-in.hbs
Forgotten password functionality. Will send a JWT via email, which can then be used for login.
> Send login link

- app/components/doi-list.js
- app/models/doi.js
- app/templates/components/doi-list.hbs
- config/environment.js
handle random doi lookup and multiple prefixes
> create draft doi

- app/components/provider-list.js
- app/components/provider-show.js
- app/models/provider.js
- app/templates/components/provider-list.hbs
- app/templates/components/provider-show.hbs
https://github.com/datacite/datacite/issues/727
> Feature billing info

- app/models/provider.js
- app/templates/components/provider-list.hbs
- app/templates/components/provider-show.hbs
https://github.com/datacite/lupo/issues/278
> adding billing contact

- app/helpers/format-contact.js
- app/templates/providers/show/settings.hbs
- tests/integration/helpers/format-contact-test.js
Closes https://github.com/datacite/bracco/issues/344.
> format contacts

- app/templates/application.hbs
- config/environment.js
- package.json
- yarn.lock
Show progress bar when loading data from api is slow.
> show loading indicator

- app/controllers/providers/new.js
- app/controllers/providers/show/edit.js
- app/controllers/providers/show/organizations/new.js
- app/models/provider.js
- app/services/current-user.js
- app/templates/providers/new.hbs
- app/templates/providers/show/edit.hbs
- app/templates/providers/show/organizations/new.hbs
- app/transforms/image.js
- config/environment.js
Working with ActiveStorage in the Rails backend API.
> support logo upload

- app/components/doi-geo-location.js
- app/components/doi-geo-locations.js
- app/controllers/dois/show/edit.js
- app/controllers/dois/show/modify.js
- app/controllers/repositories/show/dois/new.js
- app/controllers/repositories/show/dois/upload.js
- app/models/doi.js
- app/models/geo-location.js
- app/serializers/doi.js
- app/templates/components/doi-geo-location.hbs
- app/templates/components/doi-geo-locations.hbs
- app/templates/dois/show/edit.hbs
- app/templates/repositories/show/dois/new.hbs
- tests/acceptance/client_admin/doi-test.js
- tests/acceptance/staff_admin/doi-test.js
- tests/factories/doi.js
- tests/integration/components/doi-geo-location-test.js
- tests/integration/components/doi-geo-locations-test.js
enables form to submit geolocationPlace
addresses https://github.com/datacite/bracco/issues/330
- component, routes, tests and model
> geo location place field

- tests/unit/abilities/user-test.js
I've started breaking down my branch into smaller bits of work. Could one of you please check whether this is okay to be merged.
> abilities user-test

- app/controllers/dois/show/edit.js
- app/controllers/repositories/show/dois/new.js
- app/routes/dois/show/edit.js
- app/routes/repositories/show/dois/new.js
- app/services/current-user.js
- app/templates/dois/show/edit.hbs
- app/templates/repositories/show/dois/new.hbs
- config/environment.js
- tests/acceptance/staff_admin/doi-test.js
This pull request removes the feature flag for the new form
This pull request removes the feature flag `optionalFields` for the new DOI form fields, and adds a warning message to the DOI create and update pages. Closes datacite/datacite#1022.
None.
Decided to use a flash message to implement this.
> Add warning message to DOI form

- app/components/repository-transfer.js
Feedback regarding the repository transfer implementation
Suggesting a minor change that simplifies the code and avoids showing providers that can't be the target.
> Simplify search provider

- app/adapters/application.js
- app/controllers/repositories/show/dois/upload.js
- app/templates/repositories/show/dois/upload.hbs
- recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-format_2886218466/recording.har
- recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-size_686014060/recording.har
- recordings/Acceptance-staff_admin-doi_1134964664/update-draft-doi_1508057167/recording.har
- recordings/Acceptance-staff_admin-provider_521206357/updating-consortium-DC_3494094721/recording.har
- recordings/Acceptance-staff_admin-repository_4125372844/update-repository-description_3754013706/recording.har
Show API errors in file upload form
closes: https://github.com/datacite/bracco/issues/445
added a flash-warning
> fix: messages when metadata is in valid

- app/models/doi.js
- app/validators/contributor-type.js
- app/validators/resource-type.js
Add validators to address older schema versions:
- Schema 3 and contributor type "Funder"
- Another breaking change is removing resourceTypeGeneral "Film" in schema 3. 
see https://github.com/datacite/bracco/issues/454
adding validtors
> feat: add validators for older versions

- app/routes/dois/show/edit.js
add condition for null schema version.
> fix: add condition

- app/router.js
- app/templates/about.hbs
- app/templates/components/application-header.hbs
- app/templates/components/landing-page.hbs
Show Fabrica version in new About page (and Ember Inspector) to make sure the user is using the expected version when there are issues. Uses [ember-cli-app-version](https://github.com/ember-cli/ember-cli-app-version).
> Adding about page with version information

- .github/workflows/main.yml
Couple of minor mods to main.yml.
> Mods to main.yml.

- app/helpers/format-creator.js
- app/templates/components/creator-show.hbs
- app/templates/components/doi-summary.hbs
closes: issue #525
Previous pull request didn't merge due to linting error - lack of quotes around argument.
> Issue #525 - need quotes around argument.

- app/templates/providers/new.hbs
closes: issue #538.
Refined when to disable/enable the form submit button for adding users. Related to issue #523.
Tested in Safari, Chrome, and FireFox.  I think that the different behavior in FireFox was just an artifact of the differences between browsers.
> Issue #538 - cannot create users in test.

- cypress/integration/consortium_admin/settings.test.ts
- cypress/integration/organization_admin/settings.test.ts
Cypress tests are out of date with the test data on staging
Cherry-picked commits that rectified this during testing for the Github Action on PR branch
> Update Cypress to match current testing data

- tests/integration/components/bar-chart-test.js
- tests/integration/components/index-info-test.js
- tests/integration/components/month-chart-test.js
- tests/integration/components/provider-info-test.js
- tests/integration/components/repository-info-test.js
- tests/unit/models/user-test.js
Fixes several Ember tests that were expecting 2021 in the response and thus failing
> Update Ember tests for 2022

- .github/workflows/pull_request.yml
- ember-cli-build.js
- package.json
Currently PRs are not tested automatically, meaning that they have to be cloned and tested locally
This PR adds a new github action that runs the Ember and Cypress test suites against any pull request to `main`
> Add testing on pull requests

- app/components/application-header.js
- app/controllers/providers/new.js
- app/controllers/providers/show/edit.js
- app/helpers/provider-form-errors.js
- app/models/provider.js
- app/routes/providers/show/organizations/new.js
- app/services/current-user.js
- app/templates/providers/new.hbs
- app/templates/providers/show/edit.hbs
- app/templates/providers/show/organizations/new.hbs
- config/environment.js
- dotenv.js
- yarn.lock
closes: none
Update forms for addition of doi-estimate field for consortium organizations. 
Should conform to [requirements spec](https://docs.google.com/document/d/14IAGf1hQzKeY3BPsixUv78IYuQiyIAU5_nY78IThf8k/edit#heading=h.cded8372egm4) and [technical spec](https://docs.google.com/document/d/1Q8MosZn6e0xiO0pYI9QoBVkRlgeqrx7iZHn8qz3YgQ4/edit?usp=sharing).
Feature flag is off by default.  It is the ENABLE_DOI_ESTIMATE environment variable set in the vercel environment.  Value of 0 is off (default). Value of 1 is on.  
Before turning the feature flag, the doi-estimate update must be installed in lupo first and the database migration should be run to add the field to the database.
Should be reviewed in the staging environment before deployment to production and before turning on the feature …
> Doi estimate - additional field

- app/templates/dois/show/edit.hbs
- app/templates/repositories/show/dois/new.hbs
- app/validators/url-domain.js
Fixes #611
Fix the spelling of asterix on the Form page in Fabrica.
closes: #611 
> Fix the spelling of asterix on the Form page in Fabrica

- cypress/integration/client_admin/settings.test.ts
- cypress/integration/consortium_admin/settings.test.ts
- cypress/integration/organization_admin/repositories.test.ts
- cypress/integration/organization_admin/settings.test.ts
- cypress/integration/staff_admin/settings.test.ts
- tests/integration/components/doi-list-test.js
Some Cypress tests are flaky and frequently fail due to async leaks, the asynchronicity of the Ember framework, and Cypress consistency with page interactions.  
Several tests that frequently fail were changed to avoid failures related to time-sensitive page interactions. Rather than  `.click({force: true}).then(` on certain buttons, they were changed to use `cy.on("url:changed", (newUrl)`. This adjustment less rigorously tests for the correct URL change but is able to consistently pass locally. 
Multiple suggested methods for handling asynchronous changes were attempted, including using ‘wait’ and observing changes in the document before testing. 
- Consider using positive language as opposed to neutral when offering …
> Adjustments to Cypress tests for async leaks

- app/index.html
- app/templates/repositories/show/dois/new.hbs
Migrates usersnap classic to the new one for bracco
closes: datacite/datacite#1443
https://app.frontapp.com/open/msg_hjmasb9
> Migrates usersnap classic to the new one

- app/templates/components/repository-list.hbs
Just replacing the warning that I previously removed, but should not have.
> Prefix workflow. (PR mods - Replace warning previously removed.)

- app/controllers/repositories/show/prefixes/new.js
Increase number of prefixes shown in 'assign prefix' button dropdown.  Because we need this quickly, I am opening a new issue to allow this to be an environment variable so we can modify it later without code changes.
Closes Issue #630 
> Increase number of prefixes in assign prefix dropdown.

- app/components/doi-related-item-contributor.js
- app/components/doi-related-item-creator.js
- app/components/doi-related-item-identifier.js
- app/components/doi-related-item.js
- app/components/doi-related-items.js
- app/controllers/dois/show/edit.js
- app/controllers/dois/show/modify.js
- app/helpers/doi-form-errors.js
- app/models/doi.js
- app/models/related-item-contributor.js
- app/models/related-item-creator.js
- app/models/related-item-identifier.js
- app/models/related-item.js
- app/serializers/related-item.js
- app/templates/components/doi-related-item-contributor.hbs
- app/templates/components/doi-related-item-creator.hbs
- app/templates/components/doi-related-item-identifier.hbs
- app/templates/components/doi-related-item.hbs
- app/templates/components/doi-related-items.hbs
- app/templates/dois/show/edit.hbs
- app/templates/repositories/show/dois/new.hbs
- cypress/integration/client_admin/doi.test.ts
- tests/factories/doi.js
- tests/integration/components/doi-related-item-test.js
- tests/integration/components/doi-related-items-test.js
- tests/integration/components/doi-subjects-test.js
This PR adds Related Item support to the Fabrica DOI creation + edit forms, as well as tests for the Classification Code field in subjects
closes: https://github.com/datacite/datacite/issues/1401 https://github.com/datacite/datacite/issues/1402 https://github.com/datacite/datacite/issues/1403 https://github.com/datacite/datacite/issues/1404 https://github.com/datacite/datacite/issues/1405 https://github.com/datacite/datacite/issues/1410
- Ensure you give reasons for the …
> Add related item support

- .github/workflows/manual.yml
- .github/workflows/pull_request.yml
Allows manually invocation of pull_request.yml.  Prints current branch.
> Workflow tweaks.

- app/templates/components/doi-list.hbs
- app/templates/components/doi-name-identifier.hbs
- app/templates/components/model-search.hbs
- app/templates/dois/show/edit.hbs
- app/templates/dois/show/modify.hbs
- app/templates/repositories/show/dois/new.hbs
- app/templates/repositories/show/dois/upload.hbs
- cypress/integration/client_admin/doi.test.ts
- cypress/integration/consortium_admin/doi.test.ts
- cypress/integration/organization_admin/doi.test.ts
- cypress/integration/staff_admin/prefix.test.ts
- tests/integration/components/doi-contributor-test.js
- tests/integration/components/doi-creator-test.js
- tests/integration/components/doi-name-identifier-test.js
Modifies help text for URL and Name Identifier fields. Modifies Search input in-cell help text on DOI List page. 
closes: datacite/datacite#1517
For URL and Name Identifier changes, modified text in relevant templates. For changes in Search input in-cell help text on DOI List page, modified ModelSearch template to allow variable text with a default "Type to search..." value. Adjusted cypress test for flakiness that may have been caused by the ModelSearch change. 
- …
> Fabrica improvements 6

- cypress/integration/consortium_admin/info.test.ts
Fix a test in fabrica improvments 5.
> Fabrica-improvements-5: export basic metadata (rebase and fixes).

- app/components/doi-related-item-contributor.js
- app/components/doi-related-item.js
- app/models/related-item-contributor.js
- app/models/related-item.js
- app/templates/components/doi-related-item.hbs
- tests/integration/components/doi-related-item-test.js
- tests/integration/components/doi-related-items-test.js
closes:[100](https://github.com/datacite/tasks/issues/100)
- Remove unneeded contributor validations
- Set default for contributors (if added)
- Change the form setup of contributors and creators' to the creation and validation of empty fields.
- Align buttons and titles
- The REST API allows for creating DOIs without mandatory fields in the relatedItem property. This is likely to be a problem with bologense
> Related items validation

- app/components/application-header.js
- app/helpers/current-year.js
- app/templates/components/bar-chart.hbs
- app/templates/dois/show/edit.hbs
- app/templates/repositories/show/dois/new.hbs
- cypress/integration/client_admin/doi.test.ts
Fix some warnings, other cleanup, add a better test for 'future dois'.
> Fabrica Improvements - cleanup and better test.

- app/styles/local.css
- app/templates/components/create-doi-button.hbs
Changes the 'Create DOI' button to look and act more like the Front 'Compose' button.
Vercel Preview: https://bracco-7e862z6s7-datacite.vercel.app/
> Fabrica Improvements 1 - modify create-doi button.

- config/environment.js
- cypress/integration/client_admin/doi.test.ts
> Fabrica Improvements - cleanup.

- app/styles/local.css
- app/templates/components/create-doi-button.hbs
- app/templates/components/doi-list.hbs
- app/templates/repositories/show/index.hbs
- app/templates/repositories/show/prefixes/index.hbs
- app/templates/repositories/show/settings.hbs
Updated the look of the 'Create DOI' button dropdown to be more consistent.
Added icons and padding to the 'Create DOI' button dropdown.
> Fabrica Improvements 1 - Updated create-doi-button dropdown

- app/styles/local.css
Related to: https://github.com/datacite/tasks/issues/108
Fixes review comment :
> I think there is an issue with the format of the power-select. you can see you can scroll within the input field. that doesn't happen in any other compoenet (subejcts or languges)
https://bracco-mft35bhdg-datacite.vercel.app/repositories/datacite.demo/dois#thread-id=ktlic
> fabrica-improvements-review: doi formats dropdown.

- app/components/export-basic-metadata.js
- app/routes/repositories/show/dois/index.js
- app/templates/components/doi-list.hbs
- app/templates/repositories/show/dois/index.hbs
- app/utils/current-date.js
Related to: https://github.com/datacite/tasks/issues/108#issuecomment-1386064951
Fixes issue in review comment:
> Could we change the file name to something more descriptive, such as:   today_date + client_id + page_number 
https://bracco-mft35bhdg-datacite.vercel.app/repositories/datacite.demo/dois#thread-id=ktlic
> fabrica-improvements-review: export-doi-metadata change exported file name.

- .github/workflows/deploy.yml
- .github/workflows/main.yml
- .github/workflows/manual.yml
- .github/workflows/pull_request.yml
- package.json
- yarn.lock
Updated bracco github actions to remove deprecation warnings due to other github actions that use less than node 14, set-output or save-output.  The only thing not updated was edge/simple-slack-notify@master because it has not been maintained for 3 years so we need to find a new slack notifier.
Also updated caniuse-lite for better browser compatibility.
> Fabrica improvements actions

- app/controllers/providers/show/repositories/new.js
closes: #721
Add error reporting to 'Create Repository' form.
> Add error reporting to create repository form.

- app/models/repository.js
This is the same as https://github.com/datacite/bracco/pull/720 from a branch, rather than a fork.
Add entries to list in app/models/repository.js
Open Questions and Pre-Merge TODOs
> Add Service Provider integrations to repository software list

- package.json
- yarn.lock
Review dependabot and yarn audit security notices.  Fix as many as possible with module upgrades or resolution.  The status of the security notices is described [here](https://docs.google.com/document/d/1VW6nk4bJ1Dwo2NxzPG1sQUdTz236vPyR_UzbSk8uItg/edit?usp=sharing).  
closes: #742
POST-MERGE TASKS:
> v3.24 Security audit mods.

- app/templates/contacts/show/edit.hbs
- app/templates/providers/show/contacts/new.hbs
- cypress/e2e/consortium_admin/contact.test.ts
- cypress/e2e/consortium_admin/repositories.test.ts
- cypress/e2e/consortium_admin/settings.test.ts
- cypress/e2e/organization_admin/contact.test.ts
- cypress/e2e/organization_admin/repositories.test.ts
- cypress/e2e/organization_admin/settings.test.ts
- cypress/e2e/staff_admin/contact.test.ts
- cypress/support/commands.js
- cypress/support/e2e.js
The PR improves the reliability of Cypress tests and makes changes necessary to accommodate the the revised testing flow in which contacts are generated and deleted by the test suite.
closes: #752
- Contacts with roles are created at the beginning of repositories tests. 
- Other tweaks to improve flexibility and reliability of tests.
> Improves Cypress testing to accommodate the automatic removal of test contacts

- README.md
- package.json
Minor updates to readme.md.  Updated Fabrica version in package.json (to 4.3.0).
closes: #775
> Minor updates, readme.md and version number in package.json.

- app/components/application-footer.js
- app/templates/components/application-footer.hbs
- config/environment.js
- cypress/e2e/client_admin/info.test.ts
- cypress/e2e/consortium_admin/contact.test.ts
- cypress/e2e/consortium_admin/organizations.test.ts
- cypress/e2e/organization_admin/contact.test.ts
- cypress/e2e/organization_admin/info.test.ts
- cypress/e2e/organization_admin/repositories.test.ts
- cypress/e2e/staff_admin/contact.test.ts
- translations/en-us.yaml
Update the Fabrica footer to conform to the standard footer set by the new home page project, with the links as detailed in the list in [DataCite - homepage inventory](https://docs.google.com/spreadsheets/d/1Ei6A3RfYuNmNvquq5W8TGeyf5C9PEz7F7HmM-6Taba8/edit#gid=1575567007).
closes: #782 
Vercel Preview: https://bracco-irbf1pgg9-datacite.vercel.app/
Set constants for urls from config/environment.js so that they can accessed and re-used throughout the site if necessary.  Group some urls with their link names so they can be grouped in the footer.  
Used the [favicon svgs](https://fontawesome.com/icons) to access the new twitter and mastodon icons.  Access to the favicons is curreintly through bootstrap, which is very old and can't be easily updated.  There are plans to update this in the next …
> Conform to new homepage standard footer.

- ember-cli-build.js
- package.json
- yarn.lock
Related to epic https://github.com/datacite/bracco/issues/792, issue https://github.com/datacite/bracco/issues/786.
Upgrading to webpack 5 and ember-auto-import v2 will allow us to upgrade other addons, such as ember-cli-bootstrap/bootstrap, and also is what is used in Ember 4.
Follow upgrade advice:
- [Ember-auto-import upgrade guide](https://github.com/embroider-build/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md)
- [Webpack upgrade guide](https://webpack.js.org/migrate/5/#upgrade-webpack-to-5)
- [Polyfills Cheat Sheet](https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a)
Mostly involved:
- Modify the addon versions in package.json
- yarn install
- Since polyfills are not automatically added by webpack, include the node-polyfill-webpack-plugin addon.
- Correct …
> Upgrade webpack and ember-auto-import

- app/components/doi-creators.js
- app/components/doi-formats.js
- app/components/doi-sizes.js
- app/components/doi-titles.js
- app/templates/components/doi-alternate-identifier.hbs
- app/templates/components/doi-contributor.hbs
- app/templates/components/doi-date.hbs
- app/templates/components/doi-description.hbs
- app/templates/components/doi-format.hbs
- app/templates/components/doi-geo-location.hbs
- app/templates/components/doi-related-identifier.hbs
- app/templates/components/doi-related-identifiers.hbs
- app/templates/components/doi-related-item-contributor.hbs
- app/templates/components/doi-related-item-creator.hbs
- app/templates/components/doi-related-item-identifier.hbs
- app/templates/components/doi-related-item.hbs
- app/templates/components/doi-rights-list.hbs
- app/templates/components/doi-rights.hbs
- app/templates/components/doi-size.hbs
- app/templates/components/doi-subject.hbs
- app/templates/repositories/show/dois/new.hbs
- package.json
- types/bracco/index.d.ts
- types/global.d.ts
- yarn.lock
Related to epic https://github.com/datacite/bracco/issues/792, issue https://github.com/datacite/bracco/issues/786.
Make fixes necessary to get the `new doi` form working.
UPDATE MODULES:
To update to a version of ember-data-model-fragments that works with ember v3.28.  Added @types to support the typescript requirements of ember-data-model-fragments.
- ember-data-model-fragments  (5.0.0.beta-8 => ^6.0.7)
- @types/ember (^3.1.1 => 3.16.14)
- @types/ember-data (^3.1.9 => 3.16.25)
- @types/ember-data__model (3.16.8)
- @types/ember__service (3.16.9 )
RESOLUTIONS:
Typescript complained that some modules were redefining some times.  These resolutions force the modules to use the the same type definitions.
-  "**/@types/ember-feature-flags/**/@types/ember__service": "3.16.9",
- …
> Ember 3.28 - Mods for 'new doi' form

- app/components/export-basic-metadata.js
- app/components/person-base-component.js
- app/routes/edit.js
- app/styles/local.css
- app/templates/components/application-header.hbs
- app/templates/components/doi-creator.hbs
- app/templates/components/doi-funding-reference.hbs
- app/templates/components/doi-subjects.hbs
- app/templates/edit.hbs
- app/templates/providers/show/edit.hbs
- app/templates/repositories/show/dois/new.hbs
- package.json
- yarn.lock
Related to epic https://github.com/datacite/bracco/issues/792, issue https://github.com/datacite/bracco/issues/786.
Make fixes necessary to get the new and edit doi forms working.
FIX DEPRECATIONS:
- id: this-property-fallback in various files related to new/update doi forms
RESOLUTIONS:
- "**/ember-bootstrap/**/ember-focus-trap": "1.0.2" - force use of ember-focus-trap 1.0.2.  Ember bootstrap 5's requirement for ember-focus-trap-1.1.0 caused an indirect peer module requirement of ember-source 4.0 (we are on 3.28)
FORMATTING:
- Fixes to formatting issues caused by upgrade to bootstrap 5.  In particular, restore the upper right user menu.  The menu was working, but not visible due to style changes caused by bootstrap 5
OTHER FIXES:
- 'File saver not found error' - import the file saver …
> Ember 3.28 - Mods for 'new/edit' doi forms

- app/templates/password.hbs
closes: datacite/datacite#2140
> Issue datacite/2140: fix submit button on password reset page.

- config/environment.js
Enable google tag management in all environments other than development.
> Enable google tag manager for environments other than development.

- app/models/repository.js
- app/templates/providers/show/repositories/new.hbs
- app/templates/repositories/show/edit.hbs
closes: https://github.com/datacite/bracco/issues/869
> add ability to set and update a repositories analytics tracking id

- app/index.html
- app/styles/local.css
- app/templates/providers/show/repositories/new.hbs
- app/templates/repositories/show/edit.hbs
closes: https://github.com/datacite/product-backlog/issues/259
> More robust explanation of Domains feature in label in Repository settings

- app/components/doi-subject.hbs
- app/utils/fos-mappings.js
closes: https://github.com/datacite/datacite/issues/2091
> Use valid link for OECD subjects

- app/styles/local.css
closes: https://github.com/datacite/datacite/issues/1826
> Fixes off-center landing page icons

- app/models/repository.js
Update repository software list to include new Registered Service Provider integrations.
> Add RSpace and SESAR to repository software list
