datacite/bracco

.env.stage
app/components/application-header.js

`ENV.environment` is the same for `stage` and `production` deployments.

use proper header links in stage

---

app/components/doi-metadata.js

If the respone is just a string then if we want to pretty print json it needs to be json first.

Make text actually json.

---

app/controllers/clients/index.js
app/controllers/providers/index.js
app/validators/unique-client-id.js
app/validators/unique-provider-id.js

Updated the API call to include deleted accounts, and show this error message: 
```
The Client ID xxx already exists, or existed before and has been deleted. Please contact DataCite staff if you want to create an account with this Client ID.
```

show proper error message for accounts that have been deleted. #54

---

app/abilities/doi.js
app/components/doi-descriptions.js
app/components/doi-form.js
app/components/doi-titles.js
app/controllers/clients/show/dois/new.js
app/controllers/clients/show/dois/show/edit.js
app/controllers/clients/show/dois/show/enable-form.js
app/models/doi.js
app/router.js
app/templates/clients/show/dois/show/edit.hbs
app/templates/clients/show/dois/show/enable-form.hbs
app/templates/clients/show/dois/show/index.hbs
app/templates/components/doi-creator.hbs
app/templates/components/doi-descriptions.hbs
app/templates/components/doi-form.hbs
app/templates/components/doi-titles.hbs
app/templates/components/doi-types.hbs

Form disable meta

---

app/components/doi-language.js
app/controllers/dois/show/edit.js
app/controllers/repositories/show/dois/new.js
app/models/doi.js
app/serializers/doi.js
app/services/current-user.js
app/templates/components/doi-language.hbs
app/templates/dois/show/edit.hbs
app/templates/repositories/show/dois/new.hbs
config/environment.js
tests/acceptance/client_admin/doi-test.js
tests/acceptance/staff_admin/doi-test.js
tests/factories/doi.js
tests/integration/components/doi-language-test.js

addresses: https://github.com/datacite/bracco/issues/323
> As a Fabrica administrator
> I want to be able to select language metadata in an error-free fashion from the ISO369 controlled list
> So that I can have consistent language metadata in my dois metadata
- feature flag config
- integration test
- new lang component
- routes for new and edit
- serialiser

Feature language field

---

app/components/doi-description.js
app/components/doi-language.js
app/components/doi-title.js

allow free text languages to be rendered.
details in bug issue below
closes https://github.com/datacite/bracco/issues/335
-language
-title
-description

allow free text languages to be rendered

---

app/components/doi-date.js
app/components/doi-dates.js
app/controllers/dois/show/modify.js
app/controllers/repositories/show/dois/upload.js
app/helpers/doi-form-errors.js
app/models/date.js
app/models/doi.js
app/models/funding-reference.js
app/models/related-identifier.js
app/serializers/doi.js
app/templates/components/doi-alternate-identifier.hbs
app/templates/components/doi-date.hbs
app/templates/components/doi-dates.hbs
app/templates/components/doi-format.hbs
app/templates/components/doi-funding-reference.hbs
app/templates/components/doi-geo-location.hbs
app/templates/components/doi-related-identifier.hbs
app/templates/components/doi-size.hbs
app/templates/components/doi-subject.hbs
app/templates/dois/show/edit.hbs
app/templates/repositories/show/dois/new.hbs
app/validators/date-format.js
package.json
tests/unit/validators/date-format-test.js
tests/unit/validators/identifier-format-test.js
yarn.lock

Enable the form to add dates to the DOI metadata
- using EDTF validation for dates
- date component
- test, models
- minors adjustment in other components

Feature dates field

---

app/models/rights.js
app/validators/url-format.js
package.json
tests/unit/validators/url-format-test.js
yarn.lock

Zenodo DOIs frequently use `info:eu-repo/semantics/openAccess` for `rightsURI`. Our validator should validate them.

support info-uri for rights

---

app/routes/users/show.js
app/routes/users/show/info.js

change the error message when a we find not resources for a given ORCID.
Display a more informative message for researcher profile visitor.
none
none

docs: change not found message for researcher profile

---

app/components/doi-related-identifier.js
app/templates/components/doi-related-identifier.hbs

Pascal casing is generating error on selection
closes: https://github.com/datacite/bracco/issues/415
reverse part of: https://github.com/datacite/bracco/commit/56a3460cc9bd285a9e8f8f2dfd1a783f7f0d56a6

fix: reverse pascal casing

---

app/controllers/dois/show/edit.js
app/routes/dois/show/edit.js
app/serializers/doi.js
recordings/Acceptance-client_admin-doi_1416311633/update-draft-doi_1508057167/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-alternate-identfier_2444407433/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-contributor_847131258/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-format_2886218466/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-geoLocationPlace_3330462944/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-related-identifier_2083658827/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-resource-type-general_2212790731/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-rights_3222538706/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-adding-size_686014060/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-selecting-language_2341761968/recording.har
recordings/Acceptance-client_admin-doi_1416311633/visiting-the-form-and-selecting-subject_360826678/recording.har
recordings/Acceptance-staff_admin-doi_1134964664/update-draft-doi_1508057167/recording.har
recordings/Acceptance-staff_admin-provider_521206357/updating-consortium-DC_3494094721/recording.har
recordings/Acceptance-staff_admin-repository_4125372844/update-repository-description_3754013706/recording.har

Forces all DOIs updated in the form to become schema 4. 
closes: https://github.com/datacite/bracco/issues/447
All DOIs updated in the form will be transformed to schema 4. Independently of the state of the DOI (draft, registered, findable)
Looking back at the form support messages it can be seen that the form has not support schema transformation on the past. See https://app.frontapp.com/open/msg_29opdsb from 2019 ,which is related to https://github.com/datacite/datacite/issues/654
This most likely due to the form modifying the metadata fields. The schema version is not a metadata field.

feat: force all the dois updated with the form to become schema 4

---

app/validators/unique-provider-id.js

Validation of provider check if the symbol is unique even when the provider is being updated. This causes an error on updating providers.
closes: https://github.com/datacite/bracco/issues/463
Avoid validation of uniqueness for existent records.

avoid validation of existing providers

---

app/components/doi-related-identifier.js
app/validators/identifier-format.js

There was a mistake in the PURL validation regexp. 
closes: https://github.com/datacite/bracco/issues/464
We change to use URL with a whitelist of host.

fix: use url validator rather than regexp

---

app/components/doi-related-identifier.js
app/components/doi-types.js
app/validators/resource-type.js

This is to allow resource type of ResourceObject
e.g. its ResourceObject not Resource object, see schema
Also fixes Interactive resource too
Bug fix
closes: #479 
Match schema defs

Match known resource types in constants used

---

config/environment.js
package.json
yarn.lock

Google tag manager is needed to measure behaviour
Collecting behavioural data from fabrica users.
closes: https://github.com/datacite/tasks/issues/49
Using google tag manager to avoid having to instrumentalist all the code. 
Fabrica GTM configuration is already in GTM: https://tagmanager.google.com/#/container/accounts/6002015721/containers/40997071/workspaces/1
One just needs to copy the GTM Code. This configuration already filters analytics when the consent is rejected.
- GoogleTagManager (GTM) handles Consent cookie with a cookie trigger, so basically there is no need of code changes for GTM (besides the config), provided that we configure our GTM with that Trigger (already tested that as well) the consent cookie will work.
- Be humble in the language and feedback you give, ask don't …

adds google tag manager configuration

---

app/components/creator-show.js
app/templates/components/creator-show.hbs
app/templates/components/doi-summary.hbs

closes: Issue #525
The user data looks fine. This is a problem in the  Fabrica rendering code.
The sample  DOI data in the issue has more than 50 creators.   DOIs with less than 50 creators display fine.  It looks like Fabrica was trying to limit the number of creators in the display to 50.  Once the number of creators is greater than 50, the error, below, shows up in the browser console, and the page display is cut short. In this case only 3 out of 10 DOIs are displayed.
In the code, this.creators.slice makes a ’shallow copy’ of the array.  Because of this, on line 9 we are overwriting one part of the array with another part of itself.  That is being recognized as an error, and so stops display of dois on the page.
From the console:
I need someone to look at creater-show.js and verify …

Issue #525 - The DOIs tab is not rendering correctly for inist.cea

---

app/models/provider.js
app/routes/providers/show/change.js

Send a flag up to disable validations which we can then use to disable on contacts validator.
closes: #542
Allows organisations to always set password regardless of contacts.

Disable validations for contacts on password change

---

package.json

Deployments of Bracco are not being built with production mode
Updates `package.json` to add the `--environment=production` flag to the build command, because that is what Vercel uses ([Docs](https://vercel.com/docs/concepts/deployments/build-step#build-command)) 
Vercel deploy log:

Update ember build command to use production mode

---

app/templates/providers/show/contacts/index.hbs

closes: issue #562 
Fix minor problem with link parameter for pagination template in contacts tab.
A good test page is the [DataCite Consortium contacts tab](https://doi.stage.datacite.org/providers/dc/contacts) in staging.  Log in, scroll down to the bottom of that page, the paging link '2', for example, would send the user to https://doi.stage.datacite.org/contacts?page=2 instead of http://doi.stage.datacite.org/providers/dc/contacts?page=2.
- Ensure you give reasons …

Issue #562 - Fabrica paging for contacts list is not working correctly.

---

app/controllers/providers/show/prefixes/index.js
app/controllers/providers/show/prefixes/new.js
app/templates/providers/show/prefixes/index.hbs

closes: issue #634 
Adds back the button that was inadvertently taken out for the prefix workflow project.  Does appropriate testing to enable/disable the button given whether there are prefixes available to assign. 
Restores the ability of staff_admin to assign prefixes to providers.
**Has been deployed to Vercel for testing at: https://bracco-eo3x454sk-datacite.vercel.app/

Add 'Assign Prefix' button back to provider prefix list tab

---

app/controllers/providers/show/prefixes/new.js
app/controllers/repositories/show/prefixes/new.js
app/services/prefixes.js
app/templates/providers/show/repositories/new.hbs
config/environment.js
dotenv.js

closes: issues #633, #632.  
Fixes several issues:
1. Fixes the search in the 'Add Prefix' dropdowns for repositories and providers by adding the query parameter back into the '.query' call.  (In providers/<provider_id>/prefixes/new and repositories/<repository_id>/prefixes/new - 'Add Prefix', 'select from list or type to search...'.)
1. Picks up the SHOW_N_PREFIXES environment variable to allow the number of prefixes in the 'Add Prefix' dropdown to be changed without changing code.
1. Replaces the 'Add Repository' button label on the 'submit' button at the bottom of the 'create repository' form. (In providers/<provider_id>/repositories/new.)
A [sample Vercel deployment of Fabrica with these fixes](https://bracco-nhrkuxja4-datacite.vercel.app/) has been deployed to Vercel for testing.
- …

Prefix search - several fixes

---

app/templates/change.hbs
app/templates/providers/show/change.hbs
app/templates/repositories/show/change.hbs

Some of the password input fields were text inputs. This is a security risk as browsers will store previous passwords.
Closes issue #561 
I updated them to be password input types

Updated password input type from text to password

---

app/components/bar-chart.js
app/templates/components/bar-chart.hbs
tests/integration/components/index-info-test.js
tests/integration/components/provider-info-test.js
tests/integration/components/repository-info-test.js

The bar charts were hard coded to display the current year, and were still showing 2021.
Closes issue #609 
I replaced references to the hard coded year to always fetch the current year.
I also added the timestamp 00:00:00 when creating the start/end dates for the graphs, because the date was using the user's timezone and offsetting the date, resulting in the graph showing the years 2011-2021 instead of 2012-2022 in some timezones.
- Ensure you give reasons for the …

Updated bar charts to always reflect current year

---

package.json
yarn.lock

Fabrica was not building on Vercel due to missing package dependency.  Ember-cli-clipboard needed @babel/helper-string-parser.  The dependency is localized so I just added the package to devDependencies.
closes: #650 
The preview build is [here](https://vercel.com/datacite/bracco/4uEpS66SzNRHKuByXEkVQzijbTri) if you want to try it out. 

Fix vercel build - ember-cli-clipboard depends on this package.

---

app/components/doi-related-identifier.js

Adds regex detection for DOIs with a proxy (https://doi.org) to the related identifier component in the DOI edit form. This resolves an issue where DOIs with a proxy are assigned an un-editable "URL" relatedIdentifierType value instead of "DOI".
closes: #654 

Adds detection of DOI URLs to related identifier component.

---

app/components/person-base-component.js

Metadata with a creator/contributor that contained only a `name` property (without `givenName` or `familyName`) would produce a blank creator/contributor component in the DOI edit form.  
closes: #653 
`selectNameType` was being called before the name normalization step starting here:
https://github.com/datacite/bracco/blob/d074a02d7ba18c21f70a6d93b03ec09b373b137e/app/components/person-base-component.js#L18
This called `joinNameParts` before the normalization step. `joinNameParts` makes the fragment's `name` attribute a blank string in the absence of `givenName` and `familyName` attributes. When only the `name`  attribute is populated in the original metadata, this produces a blank form to the user. 
This PR normalizes the fragment metadata first, populating `givenName` and `familyName` …

Fixes issue where an empty givenName and familyName could erase name field in person base component

---

app/components/repository-show.js
app/controllers/providers/new.js
app/controllers/providers/show/edit.js
app/controllers/providers/show/organizations/new.js
app/controllers/providers/show/repositories/new.js
app/controllers/repositories/show/edit.js
app/models/provider.js
app/models/repository.js

Adds "International Organization" as a selectable option to the Organization Type dropdown for Providers. Adds "OPUS", "Pubman", "MyCoRe" as selectable options to the Software list for Repositories. 
closes: datacite/datacite#1521
I moved several repeated consts to the relevant model files. These are then imported in each relevant component and controller. I then added the requested values to the constants. 
A lupo PR will need to merged to add the "International Organization" option to the provider validations and also to display the selected software properly in bracco datacite/lupo#872  
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur …

Fabrica improvements 10

---

.github/workflows/codeql-analysis.yml
.github/workflows/deploy.yml
.github/workflows/main.yml
.github/workflows/manual.yml
.github/workflows/pull_request.yml

Upgraded GitHub actions to use Node.js 16, due to the warnings each deployment.
closes: #659
Updated the current actions from v2 to v3 and added GitHub environment variables ($GITHUB_OUTPUT)
Researched what was needed to update the GitHub Actions, found the solution in a few blogs linked below
[Upgrade Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions)
[Upgrade to Environment Variables](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files)
[Upgrade to Environment Variables](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- Consider using …

Update GitHub actions

---

app/components/model-search.js
cypress/integration/consortium_admin/doi.test.ts
cypress/integration/organization_admin/doi.test.ts

Adds a "Sort Alphabetically" option to the DOIs list. 
closes: datacite/datacite#1518
The sort option relies on lupo and Elasticsearch functionality added in this PR: datacite/lupo#887 Using the new functionality for sorting by first title will require an update to the dois index mapping and a re-index of all DataCite DOIs to function in staging and production. 
The sort is ascending, i.e. A to Z. 
See datacite/lupo#887
- Ensure you give reasons for the changes you are …

Fabrica improvements 7

---

app/helpers/current-year.js
app/models/doi.js
app/templates/dois/show/edit.hbs
app/templates/repositories/show/dois/new.hbs
config/environment.js
cypress/integration/client_admin/doi.test.ts
cypress/plugins/index.js
dotenv.js
package.json
yarn.lock

Fabrica improvement #8: Allow specified publication year for dois to be up to 5 years into the future.
closes: [datacite/datacite#1](https://github.com/datacite/datacite/issues/1519)
Vercel Preview: https://bracco-dc127st94-datacite.vercel.app/
Added changes already added by Kristian in PR #626.  Modified the cypress test under client_admin=>create doi to add a DOI published 5 years ahead of the current year.

Fabrica improvements 8 - Register DOIs into the Future

---

app/router.js
app/templates/components/creator-show.hbs
app/templates/components/user-list.hbs

Remove user profile pages from Fabrica and redirect to Commons
[Vercel Build](https://bracco-hrhdqqkxc-datacite.vercel.app/)
closes: https://github.com/datacite/datacite/issues/1522
I removed the links to the user profile pages on Fabrica and replaced them with a redirect to the Commons user page

Fabrica-improvements-11: Link user pages to Commons

---

app/components/cc-license.js

Fixes #707
DOIs with unexpected Creative Commons rightsURIs can cause Fabrica to become unresponsive. 
closes: #707 
Adds optional chaining for URI segments. 

Fixes errors when viewing DOIs with unexpected Creative Commons rightsURIs

---

.github/workflows/deploy.yml
.github/workflows/main.yml
.github/workflows/manual.yml
.github/workflows/pull_request.yml

Make CI builds more reliable. See #713 for detailed discussion of the change and the reasoning.
closes: #713 
This is branched from the latest main, which is currently ahead of what is deployed in Test and Prod, but not in Staging (afaik). We should double check the staging situation in Vercel and be prepared to roll it back to 4.0.4 if required (until #711 is finished and merged)

Only restore from cache when there's an exact hit for yarn.lock hash

---

app/components/doi-related-item-identifier.js
app/validators/identifier-format.js
cypress/e2e/client_admin/doi.test.ts

Corrects behavior where URL-format DOIs would not validate correctly in the form for relatedIdentifiers. Adds auto-detection of URL-format DOIs to relatedItemIdentifier field. 
closes: #709 
URL-format DOI regex is added to the validator for relatedIdentifier and to the identifier auto-detection for relatedItemIdentifier. 

Fix allowing URL-format DOIs in relatedIdentifier and relatedItemIdentifier fields in form

---

app/models/subject.js

This changes from getting valueURI to schemeURI.
To avoid the confusion when looking at data that has a valueURI and then opens the form, see related issue for further notes.
Without getting into redesigning this area, a simple change is to just get the schemeURI as this is less confusing.
closes: datacite/datacite#1287

Get scheme URI for subject SchemeURI field

---

app/templates/components/doi-creator.hbs
cypress/e2e/client_admin/doi.test.ts

Bug fix to include "Add another affiliation" button when editing a DOI in the form if a creator doesn't already have affiliations. 
closes: #739
Modifies a bug in the `doi-creator` template and adds a test called `is editing a doi - FORM` for the DOI `edit` route to improve e2e testing for the form. The new test can be expanded in the future to better test the continuity of data between the form and the DOI `edit` route. 
- Ensure you give reasons for the changes you …

"Add another affiliation" appears when editing a DOI in form if creator doesn't already have affiliations

---

cypress/e2e/consortium_admin/contact.test.ts
cypress/e2e/organization_admin/contact.test.ts
cypress/e2e/staff_admin/contact.test.ts
cypress/support/commands.js

Instead of leaving contacts in the staging system that are created for Cypress tests, this PR removes test contacts after tests are run. 
closes: #752
Contacts are created with a specific patten in the `familyName` attribute. After tests are completed, a Cypress command is run that searches the API for these contacts and deletes them. This does not remove them completely from the database, so the random integer range appended to `familyName` was extended to reduce collisions.
- Offer suggestions on how to improve code e.g. simplification or expanding …

Remove contacts created during Cypress tests at end of tests

---

app/templates/providers/show.hbs
app/templates/repositories/show.hbs

Selecting tabs now consistently moves caret when logged in as a Member or Repository. 
closes: #756 
While the containing `<a>` elements in the BsNav received the necessary `active` class, the `<li>` element did not unless the page was refreshed. This appears to be a known issue with ember-bootstrap and Bootstrap 4/5: https://www.ember-bootstrap.com/api/classes/Components.Nav.html This PR implements a workaround discussed here using curly braced `link-to` template objects: https://discuss.emberjs.com/t/bootstrap-active-links-and-lis/5018 
No changes were made to the Admin template because the active tab selection works appropriately in this view.
- Consider using positive language as opposed to neutral when offering …

Selecting tabs consistently moves caret when logged in as a Member or Repository

---

app/routes/dois/show.js
app/routes/providers/show.js
app/routes/repositories/show.js
cypress/e2e/client_admin/doi.test.ts
cypress/e2e/client_admin/info.test.ts
cypress/e2e/client_admin/prefixes.test.ts
cypress/e2e/client_admin/settings.test.ts
cypress/e2e/consortium_admin/contact.test.ts
cypress/e2e/consortium_admin/doi.test.ts
cypress/e2e/consortium_admin/info.test.ts
cypress/e2e/consortium_admin/organizations.test.ts
cypress/e2e/consortium_admin/prefixes.test.ts
cypress/e2e/consortium_admin/repositories.test.ts
cypress/e2e/consortium_admin/settings.test.ts
cypress/e2e/organization_admin/contact.test.ts
cypress/e2e/organization_admin/doi.test.ts
cypress/e2e/organization_admin/info.test.ts
cypress/e2e/organization_admin/prefixes.test.ts
cypress/e2e/organization_admin/repositories.test.ts
cypress/e2e/organization_admin/settings.test.ts

Previously, Fabrica would display different data when provider or consortium identifier in URL subdirectory was upper or lowercase. In Ember v3.24, this occasionally caused issues where the Ember model id would be different than the id retrieved from the store. This PR alters the routes for case-sensitive identifiers (providers, repositories, and DOIs) so that the created Ember model consistently has a lowercase identifier. 
VERCEL DEPLOYMENT: https://bracco-d4hs1htbw-datacite.vercel.app/
closes: #770 
Changes the routes for providers, repositories, and DOIs so that the identifier in the URL subdirectory/parameter is lowercased before the relevant record is retrieved. 
- Consider using positive language as opposed to …

Lowercases URL subdirectory identifiers before retrieving data from lupo

---

cypress/support/commands.js

Some Cypress test contacts appear to be created without a `family_name` and thus are not swept up by the query in `deleteProviderTestContacts`, which relies on this field. Because the `email` field consistently exists, this PR changes the query to this field. 
closes: #771 
Updates lupo query to `/contacts` endpoint for `deleteProviderTestContacts` method. 

Improve Cypress test contact deletion reliability

---

app/templates/providers/show/prefixes/new.hbs
app/templates/repositories/show/prefixes/new.hbs

Fixes for prefix assignment form behaviors where 1) prefixes did not appear as options for repositories and 2) selected prefixes did not appear as the select value. 
closes: #800 #801
Made small changes to fix what appear to be typos from the Ember 3.24 upgrade. 

Fixes for prefix assignment forms 

---

app/models/doi.js

closes: #803
Interpreting a non-standard format date was causing an error in Firefox.  It was expecting 'YYYY' and was given '999'.  '0999' works in Chrome, Firefox, and Safari.  
I also changed the conditions to use 'onOrBefore' and 'onOrAfter' instead of 'Before' and 'After'.  I think this helps the code to be a little more understandable.

Edit doi forms weren't working due to date validation problem.

---

app/models/funding-reference.js

closes: #729 
Currently we disable the validation on `funderName` when `funderIdentifier`. However, `funderIdentifier` is added automatically when you select `funderName`. Solution is to disable the validation only when the doi is in draft state

doi forms weren't showing validation error for funderName when not draft

---

app/components/doi-subject.js
app/models/subject.js

Adding and then replacing an OECD subject in the Fabrica form does not remove OECD schemeURI and valueURI from resulting metadata
closes: #646 
- set schemaURI to null when fos is empty

Remove default schemaURI when subject is custom 

---

app/components/doi-language.js
app/mixins/language-computed.js

Selected language does not display in Language property dropdown select in Fabrica form
closes: #823 
Update the language mixin to handle fragments and models

Fix doi-language model issue

---

app/routes/index.js
app/routes/providers/show.js
cypress/e2e/organization_admin/info.test.ts

closes: #820
Fabrica crashes due to inconsistent state - mostly seen during development.
Checks to make sure the flashmessages object is not being destroyed before trying to set it.

Fix crash from inconsistent browser state while display a flash message

---

cypress/e2e/organization_admin/info.test.ts

Minor alteration to test check.

---

app/components/export-basic-metadata.js

Exporting Metadata fails because of a nil publisher
closes: #844 
Add conditional check for publisher before accessing its name

Fix publisher TypeError on MetaData Export

---

app/components/export-basic-metadata.js

Fix filesaver import error on MetaData Export
closes: #846

Fix filesaver import error on MetaData Export

---

app/routes/reset.js
app/templates/sign-in.hbs

Fix typo that broke the 'forgot password' link on the sign-in page.

Fix for syntax error that broke a link on the sign-in page.

---

yarn.lock

Related to epic https://github.com/datacite/bracco/issues/792, issue https://github.com/datacite/bracco/issues/786.
Upgrades - Run the provided browser support command which adds the ability to get information from caniuse.com about browser support for a wide variety of css/javascript/etc features.
Run the command:
```
npx update-browserslist-db@latest
```
which will update yarn.lock directly to pull in the lastest caniuse-db package which is used by ember to determine browser support for various features.
- Offer suggestions on how to improve code e.g. …

Ember 3.32 - Run the browser-support command to get any updates.

---

app/models/repository.js
cypress/e2e/client_admin/info.test.ts
cypress/e2e/organization_admin/repositories.test.ts

closes: https://github.com/datacite/datacite/issues/2113
- Adds raidRegistry to permissible repository types.  This is used everywhere it is needed (create/update repository forms, displays, and the repository filter on in the left column of pages with filters).

Implements raidRegistry type for Repositories

---

app/models/creator.js

Fix for rendering error with DOIs with null nameIdentifier.
closes: #862 

Fix for rendering error with DOIs with null nameIdentifier

---

app/components/doi-doi.js
cypress/e2e/staff_admin/contact.test.ts

Fix for Fabrica form resets selected prefix when entering metadata
closes: #864
Change `didReceiveAttrs` lifecycle hook to `init` so `setDefaultPrefix` is only called when the form loads.

Fix for Fabrica form resets selected prefix when entering metadata

---

app/templates/providers/new.hbs

When creating a new provider, the email fields return an error if you accidentally have a whitespace at the end of the email (e.g if you copied/pasted it from somewhere) and don't just trim it automatically, even when the rest of the email is valid.
This issue doesn't happen on the repository creation page, which automatically trims the email field of whitespace.
Both use the same validator:
https://github.com/datacite/bracco/blob/main/app/models/repository.js#L123
https://github.com/datacite/bracco/blob/main/app/models/provider.js#L93
But are using different control types:
https://github.com/datacite/bracco/blob/main/app/templates/repositories/show/edit.hbs#L40
https://github.com/datacite/bracco/blob/main/app/templates/providers/new.hbs#L170-L172
closes: _Add github issue that originated …

Change email fields to use email control type

---

app/controllers/repositories/show/dois/index.js
app/routes/dois/index.js

Explicitly sets the default doi sorting parameter, previously this was implicitly set by passing a null or blank sort parameter to the REST API.
This is important if we ever want to change the default sorting parameter (such as in datacite/lupo/pull/1272)
Sets the default to '-updated' instead of null in relevant controllers/routes.

Explicitly set the default doi sorting parameter

---

cypress/e2e/consortium_admin/info.test.ts

closes: #917
Remove testing for specific numbers in the info tab for cypress/e2e/consortium_admin/info.test.ts.  This always breaks after the New Year.  Test only that there are 3 graphs on the page.

Y2k-type bug in test

---

.github/workflows/build.yml
.github/workflows/cypress_test.yml
.github/workflows/ember_test.yml

Upgrade the  upload/download artifact actions ahead of the deprecation of the version we currently use
Also upgrade actions/cache to v4 - v3 is not yet deprecated but I am updating anything using v2 to v4 so might as well kill two birds with one stone
closes: https://github.com/datacite/bracco/issues/916

Upgrade artifact and cache actions

---

app/controllers/sign-in.js

Trims the identification string before authentication to avoid issues with whitespace described in the issue below:
closes: https://github.com/datacite/bracco/issues/642

Trim identification string before authentication

---

app/components/doi-list.hbs
cypress/e2e/client_admin/doi.test.ts
cypress/e2e/consortium_admin/doi.test.ts
cypress/e2e/organization_admin/doi.test.ts

Based on Support feedback, adds a signpost alert on DOI pages for Member/Consortium/Consortium Organization accounts explaining how to create and update DOIs using a Repository account. Removes "No DOIs available to transfer." alert because it is confusing for new users and otherwise doesn't have much user-facing value. 
closes: https://github.com/datacite/product-backlog/issues/294

Adds alert explaining how to create and update DOIs from a Member account
